Repository micronaut-projects/micronaut-tracing, pull requests merged in 2023-10, with the labels that each got.

#393 Update to OpenTelemetry 1.30.1
  gradle/libs.versions.toml
  tracing-bom/build.gradle
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/client/MicronautHttpClientAttributesGetter.java
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/client/MicronautHttpClientTelemetryFactory.java
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/client/MicronautHttpNetClientAttributesGetter.java
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/server/MicronautHttpNetServerAttributesGetter.java
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/server/MicronautHttpServerAttributesGetter.java
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/server/MicronautHttpServerTelemetryFactory.java
  tracing-opentelemetry-kafka/src/test/groovy/io/micronaut/tracing/opentelemetry/instrument/kafka/KafkaTelemetryIntegrationSpec.groovy
  tracing-opentelemetry/build.gradle
  tracing-opentelemetry/src/main/java/io/micronaut/tracing/opentelemetry/DefaultOpenTelemetryFactory.java
  tracing-opentelemetry/src/test/groovy/io/micronaut/tracing/opentracing/instrument/util/AnnotationMappingSpec.groovy
  tracing-opentelemetry/src/test/groovy/io/micronaut/tracing/opentracing/instrument/util/HttpClientResetForTestSpec.groovy
Labels: type: dependency-upgrade

#416 build: update OT to 1.31.0
  gradle/libs.versions.toml
  tracing-bom/build.gradle
Labels: type: dependency-upgrade

#411 Fix for http status code attribute not being set for errors when tracing with opentelemetry (#410)
  tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/server/OpenTelemetryServerFilter.java
  tracing-opentelemetry-http/src/test/groovy/io/micronaut/tracing/opentelemetry/instrument/http/OpenTelemetryHttpSpec.groovy
Labels: type: improvement

#423 Fix java 21
  .editorconfig
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  tests/kotlin-tests/build.gradle
  tracing-opentelemetry-http/build.gradle
  tracing-opentelemetry-http/src/test/groovy/io/micronaut/tracing/opentelemetry/instrument/http/OpenTelemetryHttpSpec.groovy
  tracing-opentelemetry/build.gradle
Labels: relates-to: build
