Repository micronaut-projects/micronaut-tracing, pull requests merged in 2023-06, with the labels that each got.

#309 [tracing] Update common files for branch master
  .github/renovate.json
Labels: relates-to: build

#314 [tracing] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#322 fix(docs): patch opentelemtery kafka docs
  src/main/docs/guide/opentelemetry/kafka.adoc
Labels: type: docs

#325 ci: SLSA 1.7.0
  .github/workflows/release.yml
Labels: relates-to: build

#328 downgrade to kotlin 1.7.20
  gradle/libs.versions.toml
Labels: type: regression

#333 Tracing to RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
