Repository micronaut-projects/micronaut-tracing, pull requests merged in 2025-06, with the labels that each got.

#767 Update OpenTelemetry to 1.51.0
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.tracing-module.gradle
  gradle/libs.versions.toml
  tracing-bom/build.gradle
  tracing-opentelemetry-kafka/build.gradle
Labels: type: dependency-upgrade

#769 [tracing] Update common files for branch 7.1.x
  .github/workflows/release.yml
Labels: relates-to: build

#771 define depency to opentelemetry-instrumentation-api-incubator
  tracing-opentelemetry/build.gradle
Labels: type: bug
